# Generated by Django 2.0.3 on 2018-03-12 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('FINISHED', 'Finished')], max_length=64)),
                ('winner', models.CharField(blank=True, choices=[('CODEMAKER', 'Codemaker'), ('CODEBREAKER', 'Codebreaker')], max_length=64, null=True)),
                ('secret', models.TextField()),
                ('num_holes', models.IntegerField()),
                ('num_colors', models.IntegerField()),
                ('max_guesses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guess', models.TextField()),
                ('correct_position', models.IntegerField()),
                ('correct_color', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastermind.Game')),
            ],
        ),
    ]
